---
author:
  - 'Matt Cashner (sungo@pobox.com)'
build_requires:
  Test::Distribution: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-strict
no_index:
  directory:
    - inc
    - t
requires:
  POE: 0
  Test::More: 0
version: 0.03
